- hosts: localhost
  tasks:
     - name: "pip install boto and botocore"
       pip:
           name: "boto3"
           state: present
     - name: "botocore"
       pip:
           name: "botocore"
           state: present

     - name: "creating s3 bucket"
       aws_s3: 
           aws_access_key: "your_access_key_here"
           aws_secret_key: "your_secret_key_here"
           region: "ap-south-1"
           bucket: "bucket_name"
           mode: create
           permission: "public-read"
